package com.sxca.myb.common.client.StructuredService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "WebServiceInfoImpl", targetNamespace = "http://impl.webservice.ztk.modules.ggzyzt.sxca.com/")
public interface WebServiceInfoImpl {

	/**
	 * 
	 * @param requestTime
	 * @param platId
	 * @param userId
	 * @param serialNumber
	 * @param datasetCode
	 * @param xmlContent
	 * @param versionNumber
	 * @param key
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "ReceiveInfo_JYZT")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "ReceiveInfo_JYZT", targetNamespace = "http://impl.webservice.ztk.modules.ggzyzt.sxca.com/", className = "com.sxca.ggzyzt.common.client.StructuredService.ReceiveInfoJYZT")
	@ResponseWrapper(localName = "ReceiveInfo_JYZTResponse", targetNamespace = "http://impl.webservice.ztk.modules.ggzyzt.sxca.com/", className = "com.sxca.ggzyzt.common.client.StructuredService.ReceiveInfoJYZTResponse")
	public String receiveInfoJYZT(@WebParam(name = "userId", targetNamespace = "") String userId, @WebParam(name = "key", targetNamespace = "") String key,
			@WebParam(name = "serialNumber", targetNamespace = "") String serialNumber, @WebParam(name = "datasetCode", targetNamespace = "") String datasetCode,
			@WebParam(name = "XMLContent", targetNamespace = "") String xmlContent, @WebParam(name = "requestTime", targetNamespace = "") String requestTime,
			@WebParam(name = "versionNumber", targetNamespace = "") String versionNumber, @WebParam(name = "platId", targetNamespace = "") String platId);

}
