package com.sxca.myb.common.client.SmsService;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * Sms service = new Sms();
 * SmsPortType portType = service.getSmsHttpPort();
 * portType.sms(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "Sms", targetNamespace = "http://ws.flaginfo.com.cn", wsdlLocation = "file:/C:/Users/sky/Pictures/Sms.wsdl")
public class Sms_Service extends Service {

	private final static URL SMS_WSDL_LOCATION;
	private final static Logger logger = Logger.getLogger(com.sxca.myb.common.client.SmsService.Sms_Service.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.sxca.myb.common.client.SmsService.Sms_Service.class.getResource(".");
			url = new URL(baseUrl, "file:/C:/Users/sky/Pictures/Sms.wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/Users/sky/Pictures/Sms.wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		SMS_WSDL_LOCATION = url;
	}

	public Sms_Service(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public Sms_Service() {
		super(SMS_WSDL_LOCATION, new QName("http://ws.flaginfo.com.cn", "Sms"));
	}

	/**
	 * 
	 * @return returns SmsPortType
	 */
	@WebEndpoint(name = "SmsHttpPort")
	public SmsPortType getSmsHttpPort() {
		return super.getPort(new QName("http://ws.flaginfo.com.cn", "SmsHttpPort"), SmsPortType.class);
	}

}
