package com.sxca.myb.common.client.UnStructuredService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "WebServiceFileImpl", targetNamespace = "http://impl.webservice.ztk.modules.ggzyzt.sxca.com/")
public interface WebServiceFileImpl {

	/**
	 * 
	 * @param userId
	 * @param fileStream
	 * @param md5
	 * @param serialNumber
	 * @param attachmentCode
	 * @param attachmentName
	 * @param attachmentCount
	 * @param attachmentSetCode
	 * @param attachmentType
	 * @param key
	 * @param arg9
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "ReceiveFile_JYZT")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "ReceiveFile_JYZT", targetNamespace = "http://impl.webservice.ztk.modules.ggzyzt.sxca.com/", className = "com.sxca.ggzyzt.common.client.UnStructuredService.ReceiveFileJYZT")
	@ResponseWrapper(localName = "ReceiveFile_JYZTResponse", targetNamespace = "http://impl.webservice.ztk.modules.ggzyzt.sxca.com/", className = "com.sxca.ggzyzt.common.client.UnStructuredService.ReceiveFileJYZTResponse")
	public String receiveFileJYZT(@WebParam(name = "userId", targetNamespace = "") String userId, @WebParam(name = "key", targetNamespace = "") String key,
			@WebParam(name = "serialNumber", targetNamespace = "") String serialNumber, @WebParam(name = "attachmentSetCode", targetNamespace = "") String attachmentSetCode,
			@WebParam(name = "attachmentCount", targetNamespace = "") String attachmentCount, @WebParam(name = "attachmentCode", targetNamespace = "") String attachmentCode,
			@WebParam(name = "attachmentName", targetNamespace = "") String attachmentName, @WebParam(name = "attachmentType", targetNamespace = "") String attachmentType,
			@WebParam(name = "MD5", targetNamespace = "") String md5, @WebParam(name = "arg9", targetNamespace = "") String arg9, @WebParam(name = "fileStream", targetNamespace = "") byte[] fileStream);

}
